# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# specific branch build with batching
# https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#batching-ci-runs
trigger:
  batch: true
  branches:
    include:
    - master

variables:
  ortfolder: 'ort_repo'
  buildConfiguration: 'Release'

resources:
  repositories:
    - repository: 'ort_repo'
      type: github
      name: 'oss-review-toolkit/ort'
      endpoint: 'github.com_VaeterchenFrost'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  path: 's'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- checkout: 'ort_repo'
  fetchDepth: 1
  path: $(ortfolder)
- script: dir $(Build.SourcesDirectory)
  displayName: 'Inspect SourcesDirectory'
- script: |
    dir
    cd ..
    cd $(ortfolder)
  displayName: 'Running ort'